# Generated by Django 3.0.7 on 2020-09-15 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200726_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='captain',
        ),
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Team')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
