# Generated by Django 3.0.7 on 2020-09-22 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200916_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteMemberToTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_to', to='core.Team')),
                ('invite_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_from', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
